// front-vue/src/views/Auth/Login.vue
<template>
  <div id="login_wrap">
    <div class="login_box">
      <form @submit.prevent="login">
        <div class="">
          <input type="text" v-model.trim="email" />
        </div>
        <div class="">
          <input type="text" v-model.trim="password" />
        </div>
        <button type="submit">로그인</button>
      </form>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import axios from 'axios';

export default defineComponent({
  name: 'Login-page',
  setup() {
    return {};
  },
  data() {
    return {
      userid: '',
      password: '',
      email: '',
    };
  },
  methods: {
    login() {
      axios
        .post('/auth/login', {
          email: this.email,
          password: this.password,
        })
        .then((res) => {
          console.log(res);
        })
        .catch((err) => {
          console.dir(err);
        });
    },
  },
});
</script>

<style scoped lang="scss">
#login_wrap {
  height: 100vh;
  .login_box {
    width: 327px;
  }
}
</style>

// front-react/pages/Login/index.tsx
import axios from 'axios';
import React, { FormEvent, VFC } from 'react';
import { useState } from 'react';
import { useCallback } from 'react';

const Login: VFC = () => {
  const [userid, setUserid] = useState('');
  const [password, setPassword] = useState('');

  const onSubmit = useCallback((e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    axios
      .get('/')
      .then((res) => console.log(res))
      .catch((err) => console.dir(err));
  }, []);

  const onChangeUserid = useCallback(() => {}, []);
  const onChangePassword = useCallback(() => {}, []);

  return (
    <div>
      Login PAGE
      <form onSubmit={onSubmit}>
        <input type="text" value={userid} onChange={onChangeUserid} />
        <input type="text" value={password} onChange={onChangePassword} />
        <button type="submit">로그인</button>
      </form>
    </div>
  );
};

export default Login;
